### ISSUE TITLE
NoSuchElementException with README example

### ISSUE THREAD

**Issue by raabf** [vgiotsas/CommunitiesParser#1]
I tried to run CommunitiesParser with the example mentioned in `README.md`

https://github.com/vgiotsas/CommunitiesParser/blob/7c3f447e3b65d1fef93c61d4f82b3695c8d3f8db/README.md#L69-L73

However with this example an `NoSuchElementException` rises:

````shell
$ java -cp ./:./src/main/java/:/usr/share/java/args4j.jar:/usr/share/java/json-simple.jar:/usr/share/java/commons-compress.jar vgiotsas/Main --outdir output --collectors rrc00 --communities 2914:1201 --period 20180407.0000,20180410.0000 --facilities "Interxion Frankfurt (FRA1-12)"
Couldn't reach URL https://www.euro-ix.net/csv/ixp-service-matrix
java.io.FileNotFoundException: https://www.euro-ix.net/en/csv/ixp-service-matrix/
/usr/local/bin/bgpreader -w 1522965600,1523052000 -t ribs -P 86400 -c rrc00 -y 2914:1201
Annotated routes after initial pass: 31408
/usr/local/bin/bgpreader -w 1523052000,1523224800 -t ribs -c rrc00 -j 2a00:fda0::/32 -j  63.223.19.0/24 -j  193.105.241.0/24 -j  95.215.144.0/22 -j  104.90.192.0/23 -j  8$
.198.8.0/21 -j  204.93.58.0/24 -j  212.19.32.0/19 -j  185.212.173.0/24 -j  176.124.229.0/24 -j  185.130.177.0/24 -j  188.187.223.0/24 [… Truncated many other -j options]
Annotated routes after filtering: 31408
/usr/local/bin/bgpreader -w 1523224800,1523311200 -t updates -c rrc00 -j 2a00:fda0::/32 -j  63.223.19.0/24 -j  193.105.241.0/24 -j  95.215.144.0/22 -j  104.90.192.0/23 -j
82.198.8.0/21 -j  204.93.58.0/24 -j  212.19.32.0/19 -j  185.212.173.0/24 -j  176.124.229.0/24 [… Truncated many other -j options]
Exception in thread "main" java.util.NoSuchElementException
        at java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1209)
        at java.util.TreeMap$KeyIterator.next(TreeMap.java:1265)
        at vgiotsas.CommunitiesParser.writeResults(CommunitiesParser.java:117)
        at vgiotsas.CommunitiesParser.startParser(CommunitiesParser.java:93)
        at vgiotsas.Main.main(Main.java:18)
````

java version "1.8.0_181" (TM) SE Runtime Environment (build 1.8.0_181-b13)
bgpstream 1.2.0
Debian stretch

**Comment by vgiotsas** [comment]
Thanks a lot @raabf for reporting the issue.
I've implemented CommunitiesParser to work with [BGPStream v2.0](https://bgpstream.caida.org/v2-beta). This version has many performance improvements and while it's beta it's stable.
Can you test it with v2.0 and let me know if you have any issue?
